// This file must be generated by the scaffolding end placed at the root of the user's project

import * as controllerClasses from './controllers'
import * as modelClasses from './models'
import Foobar from './foobar'


const app = new Foobar(
  {
    controllerClasses,
    modelClasses,
    host: '127.0.0.1',
    port: 8000,
  },
)

app.start()
